// Code generated by "stringer -type relayError -linecomment"; DO NOT EDIT.

package uploader

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrRelayKeyNotSet-1]
	_ = x[ErrRelayTokenWrong-2]
	_ = x[ErrRelayBadFilename-3]
}

const _relayError_name = "relay: token not setrelay: token wrongrelay: bad filename"

var _relayError_index = [...]uint8{0, 20, 38, 57}

func (i relayError) String() string {
	i -= 1
	if i < 0 || i >= relayError(len(_relayError_index)-1) {
		return "relayError(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _relayError_name[_relayError_index[i]:_relayError_index[i+1]]
}
