// Code generated by "stringer -type envError -linecomment"; DO NOT EDIT.

package env

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrCosBase64EnvNotSet-1]
	_ = x[ErrCosBase64ParseFail-2]
	_ = x[ErrBucketURLNotSet-3]
	_ = x[ErrServiceURLNotSet-4]
}

const _envError_name = "env: COS_BASE64 not setenv: COS_BASE64 parse failenv: bucket URL not setenv: service URL not set"

var _envError_index = [...]uint8{0, 23, 49, 72, 96}

func (i envError) String() string {
	i -= 1
	if i < 0 || i >= envError(len(_envError_index)-1) {
		return "envError(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _envError_name[_envError_index[i]:_envError_index[i+1]]
}
