name: Docker Image CI

on:
  release:
    types:
      - created
      - published
jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:

      - name: Print
        run: |
          echo $GITHUB_REF_NAME
          echo '{{ github.event }}'

#      - uses: dsaltares/fetch-gh-release-asset@master
#        with:
#          repo: ${{ github.repository }}
#          version: ${{ github.event.id }}
#          file: 'cos-uploader-linux-amd64'
#          token: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Build the Docker image
#        run: docker build --file build/Dockerfile --tag a-tag .
#
#      - name: Tag image
#        run: docker tag a-tag $DOCKERHUB_USERNAME/cos-uploader:$GITHUB_REF_NAME
#
#      - name: Docker login
#        if: ${{ !github.event.draft }}
#        run: echo '{{ github.event }}'
##        run: echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
#
#      - name: Docker push
#        if: ${{ !github.event.draft }}
#        run: echo pub
##        run: docker push $DOCKERHUB_USERNAME/cos-uploader:$GITHUB_REF_NAME
