name: Docker Image CI

on:
  release:
    types:
      - published
jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:

      - name: Print
        run: |
          echo Github Ref name $GITHUB_REF_NAME
          echo Release ID '${{ github.event.id }}'

      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: ${{ github.repository }}
          version: ${{ github.event.id }}
          file: 'cos-uploader-linux-amd64'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build --file build/Dockerfile --tag a-tag .

      - name: Tag image
        run: docker tag a-tag $DOCKERHUB_USERNAME/cos-uploader:$GITHUB_REF_NAME

      - name: Docker login
        run: echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin

      - name: Docker push
        run: docker push $DOCKERHUB_USERNAME/cos-uploader:$GITHUB_REF_NAME
