name: Docker Image CI

on:
  push:
jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3

      - name: aa
        run: ls

      - name: Build the Docker image
        run: docker build --file build/Dockerfile --tag $DOCKERHUB_USERNAME/cos-uploader:$GITHUB_REF_NAME .

      - name: Docker login
        run: echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin

      - name: Docker push
        run: docker push $DOCKERHUB_USERNAME/cos-uploader:$GITHUB_REF_NAME
