name: Docker Image CI

on:
  release:
    types:
      - published
jobs:

  build:
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download release artifact
        run: |
          curl https://github.com/${{ github.repository }}/releases/download/$GITHUB_REF_NAME/cos-uploader-linux-amd64 -L --output cos-uploader
          chmod 0755 cos-uploader

      - name: Build the Docker image
        run: docker build --file build/Dockerfile --tag a-tag .

      - name: Tag image
        run: docker tag a-tag $DOCKERHUB_USERNAME/cos-uploader:$GITHUB_REF_NAME

      - name: Docker login
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin

      - name: Docker push
        run: docker push $DOCKERHUB_USERNAME/cos-uploader:$GITHUB_REF_NAME
